version: '3.3'

services:
  database:
    image:
      postgres
    container_name: db
    networks:
      - cloud
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=RoflanParol
      - POSTGRES_DB=ludik_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data



  application:
      image:
        application-image
      container_name: application_1
      networks:
        - cloud
      ports:
        - "80:8080"
      depends_on:
        - database
      environment:
        - "SPRING_DATASOURCE_USERNAME=postgres"
        - "SPRING_DATASOURCE_PASSWORD=RoflanParol"
        - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ludik_db"



networks:
  cloud:
    external: true

volumes:
  postgres_volume:
    external: true


